

export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'
export const RESET_COUNTER = 'RESET_COUNTER'



export const USERS_FETCH_REQUESTED = 'USERS_FETCH_REQUESTED'
export const USERS_FETCH_SUCCEEDED = 'USERS_FETCH_SUCCEEDED'
export const USERS_FETCH_FAILED = 'USERS_FETCH_FAILED'

